# Generated by Django 6.0 on 2025-12-24 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_project_member'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_member',
            new_name='assigned_to',
        ),
    ]
